### ISSUE TITLE
This repo should be archived

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/eiffel-store#10]
### Description

We (Eiffel TC) don't see that there are any active maintainers on this repo. Therefore we intend to move it to [archived](https://github.com/eiffel-community/community/blob/master/PROJECT_LIFECYCLE.md#stage-archived) state. See more here: https://docs.github.com/en/repositories/archiving-a-github-repository

If you disagree on this, please make a comment in this issue or contact Eiffel TC about it, on eiffel-tc@googlegroups.com. If we don't hear anything within 4 weeks from today this repo will be archived.

cc @eiffel-community/eiffel-store-maintainers 

### Tasks

- [x] Create issue in the repository to be archived. See [This repo should be archived eiffel-store#10](https://github.com/eiffel-community/eiffel-store/issues/10) for an example
- [x] Create a PR that updates the Readme with the following changes:
   - [x] Change the badge to the archived badge 
- [x] Close all issues
- [x] Close all PRs
- [x] Open a PR to in the [eiffel-community/eiffel-community.github.io](https://github.com/eiffel-community/eiffel-community.github.io) repository to remove it from [https://eiffel-community.github.io/community.html](https://eiffel-community.github.io/community.html)
- [x] Delete the team under https://github.com/orgs/eiffel-community/teams Leaving the team can cause confusion on if the repository has maintainers or not. Removing the team makes this clear.
- [x] Open a PR in the [eiffel-community/community](https://github.com/eiffel-community/community) repository to update [PROJECTS.md#project-facts](./PROJECTS.md#project-facts)
  - [x] Marking the repository as archived
  - [x] Remove the Team link
- [x] Follow the instructions on https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

**Comment by m-linner-ericsson** [comment]
As with no objections raised we will archive this repo.

**Comment by m-linner-ericsson** [comment]
As per TC discussion opening again to be closed when all things are ready for archive
